name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling:latest
    
    steps:
    - name: Install Core Dependencies
      run: |
        apt-get update
        apt-get install -y wget tar curl gnupg apt-transport-https ca-certificates
        
    - name: Install Development Tools
      run: |
        # Python
        apt-get install -y python3 python3-pip python3-dev
        # Node.js
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        # Other dev tools
        apt-get install -y git build-essential
        
    - name: Install ZeroTier and Dependencies
      run: |
        # Unduh dan instal libssl1.1 karena tidak ada di kali-rolling terbaru
        wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
        dpkg -i libssl1.1_1.1.1w-0+deb11u1_amd64.deb || apt-get install -f -y
        # Unduh ZeroTier versi terbaru
        wget https://download.zerotier.com/debian/buster/pool/main/z/zerotier-one/zerotier-one_1.14.0_amd64.deb
        # Instal ZeroTier
        dpkg -i zerotier-one_1.14.0_amd64.deb || apt-get install -f -y
        # Jalankan ZeroTier daemon secara manual
        /usr/sbin/zerotier-one -d &
        # Tunggu daemon mulai
        sleep 5
        # Bergabung ke jaringan
        zerotier-cli join ${{ secrets.ZEROTIER_NETWORK_ID }}
        # Verifikasi
        zerotier-cli info
        zerotier-cli listnetworks
    
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    
    - name: Extract ngrok
      run: tar -xzf ngrok.tgz
    
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    
    - name: Setup SSH
      run: |
        apt-get install -y openssh-server
        ssh-keygen -A
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
        echo "root:1234" | chpasswd
        /usr/sbin/sshd -D &
    
    - name: Check SSH Status
      run: |
        sleep 5
        ps aux | grep sshd || echo "SSHD not running"
        netstat -tuln | grep 22 || echo "Port 22 not open"
    
    - name: Create Tunnel
      run: |
        ./ngrok tcp 22 &
        sleep 5
        curl -s http://localhost:4040/api/tunnels | grep -o "tcp://[^\"]*"

    - name: Keep Alive
      run: |
        echo "SSH tunnel is running. Connect using the ngrok URL above."
        sleep 360000
