name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling:latest
    
    steps:
    - name: Install Core Dependencies
      run: |
        apt-get update
        apt-get install -y wget tar curl gnupg apt-transport-https ca-certificates
        
    - name: Install Development Tools
      run: |
        # Python
        apt-get install -y python3 python3-pip python3-dev
        # Node.js
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        # Other dev tools
        apt-get install -y git build-essential
        
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    
    - name: Extract ngrok
      run: tar -xzf ngrok.tgz
    
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    
    - name: Setup SSH
      run: |
        # Install openssh-server
        apt-get install -y openssh-server
        # Create SSH directory and set permissions
        mkdir -p /run/sshd
        chmod 755 /run/sshd
        # Configure SSH
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        echo "root:P@ssw0rd!" | chpasswd
        # Start SSH server manually
        /usr/sbin/sshd -D &    # Run in background
    
    - name: Create Tunnel
      run: ./ngrok tcp 22
